version: '3'
services:
  mkdocs:
    build: .
    volumes:
      - ./site:/app/site
    restart: "no"
    container_name: kb-mkdocs
    pull_policy: build
  httpd:
    image: httpd:2.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./site:/usr/local/apache2/htdocs
    restart: "unless-stopped"
    container_name: kb-httpd