site_name: Tyler's Knowledge Base
site_url: https://docs.tylerharrison.dev/
repo_url: https://github.com/tyleraharrison/docs.tylerharrison.dev
repo_name: docs.tylerharrison.dev
site_description: A collection of notes and guides for various topics.
site_author: Tyler Harrison
remote_branch: main
edit_uri: 'edit/main/docs/'

nav:
    - Home: index.md
    - Docker: docker.md
    - Linux: linux.md
    - Git: git.md
    - Python: python.md
    - CTF/Hacking: ctf-hacking.md
    - Cybersecurity: cybersecurity.md
    - Networking: networking.md
    - Self Hosting:
        - self-hosting/index.md
        - Hosting Services: self-hosting/hosting.md
        - Reverse Proxy: self-hosting/reverse-proxy.md
        - Home Assistant: self-hosting/home-assistant.md
        - Plex: self-hosting/plex.md
        - Pi-hole: self-hosting/pi-hole.md
        - WireGuard: self-hosting/wireguard.md
    - Cheatsheets:
        - cheatsheets/index.md
        - Proxmox: cheatsheets/proxmox.md
    - Miscellaneous: misc.md

theme:
    name: material
    icon:
        logo: material/book-open-variant
        repo: fontawesome/brands/github
    favicon: assets/images/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.indexes
        - navigation.top
        - toc.integrate
        - toc.follow
        - content.action.edit
        - content.action.view
        - content.code.copy
    palette:
    # Palette toggle for dark mode
    -   scheme: slate
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
        primary: indigo
        accent: indigo
    # Palette toggle for light mode
    -   scheme: default
        toggle:
            icon: material/brightness-7 
            name: Switch to dark mode
        primary: indigo
        accent: indigo

plugins: 
    - social
    - search
    - glightbox

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 

extra_css:
    - assets/stylesheets/extra.css
