site_name: Tyler's Knowledge Base
site_url: https://docs.tylerharrison.dev/
nav:
    - Home: index.md
    - Docker: docker.md
    - Linux: linux.md
    - Git: git.md
    - Python: python.md
    - CTF/Hacking: ctf-hacking.md
    - Cybersecurity: cybersecurity.md
    - Networking: networking.md
    - Self Hosting:
        - self-hosting/index.md
        - Hosting Services: self-hosting/hosting.md
        - Reverse Proxy: self-hosting/reverse-proxy.md
        - Home Assistant: self-hosting/home-assistant.md
        - Plex: self-hosting/plex.md
        - Pi-hole: self-hosting/pi-hole.md
        - WireGuard: self-hosting/wireguard.md
    - Kubernetes: kubernetes.md
    - Cheatsheets:
        - cheatsheets/index.md
        - Proxmox: cheatsheets/proxmox.md
    - Miscellaneous: misc.md
theme:
    name: material
    icon:
        logo: material/book-open-variant
    favicon: assets/images/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.indexes
        - navigation.top
        - toc.integrate
        - toc.follow
    palette:
    # Palette toggle for dark mode
    -   scheme: slate
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
        primary: indigo
        accent: indigo
    # Palette toggle for light mode
    -   scheme: default
        toggle:
            icon: material/brightness-7 
            name: Switch to dark mode
        primary: indigo
        accent: indigo

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

extra_css:
    - assets/stylesheets/extra.css
